### ISSUE TITLE
Components props order matters

### ISSUE THREAD

**Issue by AntonPuko** [LoicMahieu/react-styled-flexboxgrid#44]
Hi, nice lib. But, here is a really confusing behavior:
`<Col md={3} sm={6} xs={12}>`  - doesn't work
` <Col xs={12} sm={6}  md={3}>` - work.
Its the first time ever I see that the order of props has importance. :(

**Comment by LoicMahieu** [comment]
Due to `Object.keys()` used here
 https://github.com/LoicMahieu/react-styled-flexboxgrid/blob/master/src/components/Col.js#L41

We map all keys given in props and generate media queries for each. I think I thought at the time that it is not a good idea... ^^ Depending on keys order is a terrible idea.

We could sort the keys but how? Breakpoints keys come from the config and can be modified by the developper.
I hope find a another solution that hard-code an array with the sorted keys.

Any idea?
I don't think I could find time for implement it so, feel free to propose a pull request ;)
